#!/bin/bash

case "$(uname -s)" in
  Darwin)
    defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources | egrep -w 'KeyboardLayout Name' | awk -F '=' '{print $2}' | sed -E 's/[^a-zA-Z ]//g' | awk '{$1=$1};1' | cut -c 1-3 | tr '[:lower:]' '[:upper:]'
    ;;
  Linux)
    # setxkbmap -print | grep xkb_symbols | awk '{print $4}' | awk -F"+" '{print $2}' | tr '[:lower:]' '[:upper:]'
    swaymsg -t get_inputs urgent enable | jq -r '[.[] | select(.xkb_active_layout_name != null) | .xkb_active_layout_name][0]' | cut -c 1,2 | tr '[:lower:]' '[:upper:]'
    ;;
esac
