#!/bin/bash

declare -i index=16

if [[ -z ${DEBUG+x} ]]
then
  echo '#!/bin/bash'
  echo
fi

config=(
#      1      2      3      4      5      6      7      8
# normal
  000000 a65c59 728c54 a6845e 4e82a2 b1597d 54969c 888888
  3e3e3e a97660 8b8423 998a66 6174a8 82779c 5d8979 686868
# background
  1c1c1c 371d1b 232f18 2e291f 1c2643 381a38 142c2f 2a2a2a
  1c1c1c 35241d 312f0c 312d21 21283b 2b2636 1f2e28 2a2a2a
# S    L
  0    0  # WAVE 1: normal
  0  -10  #         dim (obtained by adding S and L to normal colors)
  0    0  #         background
  35   2  # WAVE 2: normal
  35 -15  #         dim (obtained by adding S and L to normal colors)
  20   1  #         background
)

color_super80_render "${config[@]}" |
  while read -r hex
  do
    if [[ -z ${DEBUG+x} ]]
    then
      echo "echo -en \"\\e]4;$index;$hex\\e\\\\\""
      >&2 echo "$index: $hex"
    else
      printf "$index: "
      printf "\\e[48;2;$((16#${hex:1:2}));$((16#${hex:3:2}));$((16#${hex:5:2}))m$hex$(tput sgr0)"
      echo
    fi
    index+=1
  done
