#!/bin/bash

declare -i items=8

print_fg() {
  declare -i items_in_line=0
  for c in $(seq $1 $2)
  do
    tput setaf $c
    printf '%-12s' "color_$c"
    items_in_line+=1
    if [[ $items_in_line -ge $items ]]
    then
      items_in_line=0
      echo
    fi
  done
}

print_bg() {
  local fg
  for c in $(seq $1 $2)
  do
    fg=$(( $c - $3 ))
    printf "$(tput setab $c)$(tput setaf $fg) "
    printf '%-8s' "color_${fg}"
    printf " $(tput sgr0)  "
  done
  echo
}

echo "$(tput sgr0)"

print_fg  0   7
print_fg  8  15
print_fg 16  23
print_fg 24  31
echo
print_bg 16 23 16
print_bg 16 23  8
print_bg 24 31 24
print_bg 24 31 16
echo
print_fg  32 207
print_fg 208 231
print_fg 232 255
