#!/bin/bash

main() {
  local base="$1"
  local h_add="${2:-0}"
  local s_add="${3:-0}"
  local l_add="${4:-0}"
  local hsl_csv="$(parse_hsl "$base")"
  local hsl_components
  IFS=', ' hsl_components=($hsl_csv)
  local hsl_h="${hsl_components[0]}"
  local hsl_s="${hsl_components[1]::-1}"
  local hsl_l="${hsl_components[2]::-1}"
  local hsl_h_int="${hsl_h%.*}"
  local hsl_s_int="${hsl_s%.*}"
  local hsl_l_int="${hsl_l%.*}"
  local hsl_h_mod="$(( $hsl_h_int + $h_add ))"
  local hsl_s_mod=0
  local hsl_l_mod=0
  if [[ "$hsl_s_int" == 0 && "$hsl_l_int" != 0 ]]
  then
    hsl_l_mod=$(( $hsl_l_int + $l_add + 10 ))
  else
    hsl_l_mod="$(( $hsl_l_int + $l_add ))"
    hsl_s_mod="$(( $hsl_s_int + $s_add ))"
  fi
  pastel format hex "hsl($hsl_h_mod, $hsl_s_mod%, $hsl_l_mod%)"
}

parse_hsl() {
  # pastel output format:
  # hsl(a, b.c%, d.e%)
  local hsl_raw="$(pastel format hsl "$1")"
  local hsl_1="${hsl_raw:4}"
  local hsl_2="${hsl_1::-1}"
  echo "$hsl_2"
}

main "$@"
