#!/bin/bash

parse_hsl() {
  # pastel outputs hsl in format: hsl(a, b.c%, d.e%)
  local hsl_raw="$(pastel format hsl "$1")"
  local hsl_1="${hsl_raw:4}"
  local hsl_2="${hsl_1::-1}"
  echo "$hsl_2"
}

mod_one() {
  local base="$1"
  local h_add="${2:-0}"
  local s_add="${3:-0}"
  local l_add="${4:-0}"
  local hsl_csv="$(parse_hsl "$base")"
  local hsl_components
  IFS=', ' hsl_components=($hsl_csv)
  local hsl_h="${hsl_components[0]}"
  local hsl_s="${hsl_components[1]::-1}"
  local hsl_l="${hsl_components[2]::-1}"
  local hsl_h_int="${hsl_h%.*}"
  local hsl_s_int="${hsl_s%.*}"
  local hsl_l_int="${hsl_l%.*}"
  local hsl_h_mod="$(( $hsl_h_int + $h_add ))"
  local hsl_s_mod="$(( $hsl_s_int + $s_add ))"
  local hsl_l_mod="$(( $hsl_l_int + $l_add ))"
  pastel format hex "hsl($hsl_h_mod, $hsl_s_mod%, $hsl_l_mod%)"
}

octet() {
  local s_add="$1"
  local l_add="$2"
  local hex
  shift 2
  for color in "$@"
  do
    if [[ $s_add == 0 && $l_add == 0 ]]
    then
      hex="$color"
    else
      hex="$(mod_one "$color" 0 "$s_add" "$l_add")"
    fi
    # echo "echo -en \"\\e]4;$index;$hex\\e\\\\\""
    >&2 echo "$index -> $hex"
    printf "\\e]4;$index;$hex\\e\\\\\n"
    index+=1
  done
}

heatmap() {
  local h_add
  for h_add in `seq 1 24`
  do
    local hue="$(printf '%.0f' "$(echo "$h_add * 15" | bc -l )")"
    local hex="$(mod_one "$1" "$hue" 0 0)"
    >&2 echo "$index -> $hex"
    printf "\\e]4;$index;$hex\\e\\\\\n"
    index+=1
  done
}

main() {
  echo "if [[ \"\$TERM\" != 'linux' ]]; then"
  printf "echo -en \""
  octet 0   0 "${bgn[@]}"
  octet 0   0 "${bga[@]}"
  octet 0  15 "${fgn[@]}"
  octet 0  15 "${fga[@]}"
  octet 0 -15 "${fgn[@]}"
  octet 0 -15 "${fga[@]}"

  octet 35   0 "${fgn[@]}"
  octet 35   0 "${fga[@]}"
  octet 35   0 "${bgn[@]}"
  octet 35   0 "${bga[@]}"
  octet 35  10 "${fgn[@]}"
  octet 35  10 "${fga[@]}"
  octet 35 -15 "${fgn[@]}"
  octet 35 -15 "${fga[@]}"

  heatmap b04f4f
  heatmap c63939
  heatmap d92626
  heatmap ec1313
  echo '"'
  echo 'fi'
}

fgn=(000000 a65c59 728c54 a6845e 4e82a2 b1597d 54969c 888888)
fga=(3e3e3e a97660 8b8423 998a66 6174a8 82779c 5d8979 686868)

bgn=(1c1c1c 371d1b 232f18 2e291f 1c2643 381a38 142c2f 2a2a2a)
bga=(1c1c1c 35241d 312f0c 312d21 21283b 2b2636 1f2e28 2a2a2a)

declare -i index=16
main $@
