#!/usr/local/bin/bash

_target="$1"
[ -z "$_target" ] && echo "Error: No target" 1>&2 && exit 1

_path="$HOME/projects/endowus/silver-server/.view/$_target"

[ -d "$_path" ] && tmux new-window -c "$_path" -n $(echo "${_target^^}") || echo "Error: Directory $_path does not exist." 1>&2 && exit 1
