#! /bin/bash

defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources | egrep -w 'KeyboardLayout Name' | awk -F '=' '{print $2}' | sed -E 's/[^a-zA-Z ]//g' | awk '{$1=$1};1' | cut -c 1-3 | tr '[:lower:]' '[:upper:]'
