#! /bin/bash

defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources | egrep -w 'KeyboardLayout Name' | awk -F '=' '{print $2}' | awk -F '\"' '{print $2}' | cut -c 1-2 | tr '[:lower:]' '[:upper:]'
