#!/bin/bash

_app=

case $(uname -s) in
  'Darwin')
    _app="$(osascript << 'EOF'
global frontApp, frontAppName

tell application "System Events"
    set frontApp to first application process whose frontmost is true
    set frontAppName to name of frontApp
end tell

return frontAppName
EOF
)"
    ;;
  'Linux')
    _app="$(xdotool getactivewindow getwindowname)"
    ;;
esac

_app_lower_case="${_app,,}"
if [[ "$_app_lower_case" == 'alacritty' || "$_app_lower_case" == 'iterm2' ]]
then
  echo '1'
fi
