#!/bin/bash

case $(uname -s) in
  'Darwin')
    _summary="$(/usr/bin/python -c 'import Cocoa; print Cocoa.NSEvent.modifierFlags() & Cocoa.NSAlphaShiftKeyMask ')"
    if [[ (($_summary > 0)) ]]
    then
      echo "CAPS"
    fi
      ;;
esac
