#!/usr/local/bin/bash

declare -A MAP

for FIELD in host port database; do
  MAP[$FIELD]=$(cat ~/projects/dsn.conf.yaml | yq r - "$1.$FIELD");
done

mongo --quiet "mongodb://${MAP[host]}:${MAP[port]}/${MAP[database]}"
