#!/bin/bash

nvimSocketNamePrefix="/tmp/nvimsocket"

NAME="$1"; shift

if [[ -z "$NAME" ]]
then
  >&2 echo 'No target pipe'
  exit 1
fi

SERVERNAME="${nvimSocketNamePrefix}-${NAME}"

if [ ! -e "$SERVERNAME" ]
then
  >&2 echo "File $SERVERNAME does not exist"
  exit 1
fi

ARGS=`getopt --name 'nvim-pipe' --options 'sc' --longoptions syntax:,comment: -- "$@"`
eval set -- "$ARGS"

_syntax=
_comment=

while true
do
  case "$1" in
    --syntax)
        case "$2" in
          "")
            shift 2 ;;
          *)
            _syntax="$2"
            shift 2 ;;
        esac ;;
    --comment)
      case "$2" in
          "")
            shift 2 ;;
          *)
            _comment="$2"
            shift 2 ;;
      esac ;;
    --)
      shift
      break ;;
    *)
      >&2 echo "Error parsing args"
      exit 1 ;;
  esac
done

_syntax_conf=
if [[ -z "${_syntax}" ]]
then
  _syntax_conf="nofoldenable"
else
  _syntax_conf="syntax=${_syntax} foldenable "
fi

_configure="<esc>:setlocal buftype=nofile bufhidden=hide viminfo= noswapfile ${_syntax_conf}<cr>"

if [[ -z "${_comment}" ]]
then
  _comment_content='<esc>G'
else
  _comment_content="<esc>i${_comment}<cr><cr><esc>"
fi

nvr --remote-send "${_configure}${_comment_content}" - --servername "$SERVERNAME"
