#!/usr/local/bin/bash

declare -A MAP

_psql_params=
_csv_params='--no-align --field-separator "," --pset footer'

case "$2" in
  --csv) _psql_params=$_csv_params
esac

for FIELD in host port database username password; do
  MAP[$FIELD]=$(cat ~/projects/dsn.conf.yaml | yq r - "$1.$FIELD");
done

eval "PGPASSWORD=${MAP[password]} psql ${_psql_params} --host=${MAP[host]} --port=${MAP[port]} ${MAP[database]} ${MAP[username]}"
