#!/usr/local/bin/bash

declare -A MAP

for FIELD in host port database username password; do
  MAP[$FIELD]=$(cat ~/projects/dsn.conf.yaml | yq r - "$1.$FIELD");
done

eval "PGPASSWORD=${MAP[password]} psql --no-align --field-separator "," --pset footer --host=${MAP[host]} --port=${MAP[port]} ${MAP[database]} ${MAP[username]}"
