#!/bin/bash

if [[ -f .gitbase ]]
then
  base_branch_name=$(cat .gitbase | head -n 1)
  if [[ -z "$base_branch_name" ]]
  then
    >&2 echo 'no target branch'
  else
    >&2 echo "-> $base_branch_name"
    git rebase -i "$base_branch_name"
  fi
fi
