#!/bin/bash

_context="$(kubectl config current-context)"
_namespace="$(kubectl config view --minify --output 'jsonpath={..namespace}')"
if [[ ! -z "$_namespace" ]]
then
  echo "${_namespace}@${_context##*_}"
else
  echo "${_context##*_}"
fi
