#! /bin/bash

case $(uname -s) in
  'Darwin')
    defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources | egrep -w 'KeyboardLayout Name' | awk -F '=' '{print $2}' | sed -E 's/[^a-zA-Z ]//g' | awk '{$1=$1};1' | cut -c 1-3 | tr '[:lower:]' '[:upper:]'
    ;;
  'Linux')
    setxkbmap -print | grep xkb_symbols | awk '{print $4}' | awk -F"+" '{print $2}' | tr '[:lower:]' '[:upper:]'
    ;;
esac
