#!/bin/bash

_app=

case $(uname -s) in
  'Darwin')
    _app="$(osascript << 'EOF'
global frontApp, frontAppName

tell application "System Events"
    set frontApp to first application process whose frontmost is true
    set frontAppName to name of frontApp
end tell

return frontAppName
EOF
)"
    ;;
  'Linux')
    if [[ -z "$WAYLAND_DISPLAY" ]]
    then
      _app="$(xdotool getactivewindow getwindowname)"
    else
      _app="$(gdbus call \
        --session \
        --dest org.gnome.Shell \
        --object-path /org/gnome/Shell \
        --method org.gnome.Shell.Eval "
          global
            .get_window_actors()
            .map(a=>a.meta_window)
            .find(w=>w.has_focus())
            .get_wm_class()" \
        | cut -d'"' -f 2)"
    fi
    ;;
esac

_app_lower_case="${_app,,}"
if [[ "$_app_lower_case" == 'alacritty' || "$_app_lower_case" == 'iterm2' ]]
then
  echo '1'
fi
