#!/bin/bash

while true
do
  _time="$(date +'%l:%M')"
  _date="$(date +'%a %d')"
  _title="$(swaymsg -t get_tree 2>/dev/null | jq -r '..|try select(.focused == true).name' 2> /dev/null | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g')"
  echo "<span foreground='#606060' font-family='sans'>${_title}</span>          <span foreground='#777777'>${_time}</span>  <span foreground='#506060'>${_date}</span>    "
  sleep 2
done
