#!/bin/bash

batteryState() {
  case "$(uname -s)" in
    Darwin)
      ioreg -c AppleSmartBattery -w0 | \
      grep -o '"[^"]*" = [^ ]*' | \
      sed -e 's/= //g' -e 's/"//g' | \
      sort |
      {
      while read key value; do
          case "$key" in
              'MaxCapacity') _MAX_CAP=$value; ;;
              'CurrentCapacity') _CURR_CAP=$value; ;;
              'ExternalConnected') if [ "$value" = 'Yes' ]; then _CONN_CHAR='▲'; else _CONN_CHAR='▼'; fi ;;
          esac
      done
      echo "${_CONN_CHAR} $(( 100 * $_CURR_CAP / $_MAX_CAP ))%"
      }
      ;;
    *)
      ;;
  esac
}

inputSource() {
  case "$(uname -s)" in
    Darwin)
      defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleSelectedInputSources | egrep -w 'KeyboardLayout Name' | awk -F '=' '{print $2}' | sed -E 's/[^a-zA-Z ]//g' | awk '{$1=$1};1' | cut -c 1-3 | tr '[:lower:]' '[:upper:]'
      ;;
    Linux)
      # setxkbmap -print | grep xkb_symbols | awk '{print $4}' | awk -F"+" '{print $2}' | tr '[:lower:]' '[:upper:]'
      swaymsg -t get_inputs urgent enable | jq -r '[.[] | select(.xkb_active_layout_name != null) | .xkb_active_layout_name][0]' | cut -c 1,2 | tr '[:lower:]' '[:upper:]'
      ;;
  esac
}

k8sState() {
  _context="$(kubectl config current-context)"
  _namespace="$(kubectl config view --minify --output 'jsonpath={..namespace}')"
  if [[ ! -z "$_namespace" ]]
  then
    echo "${_namespace}@${_context##*_}"
  else
    echo "${_context##*_}"
  fi
}

wireguardState() {
  case "$(uname -s)" in
    Darwin)
      _session_artifact_name="$(find -f /var/run/wireguard/*.name)"
      if [[ ! -z "$_session_artifact_name" ]]
      then
        _file_name="${_session_artifact_name##*/}"
        _profile_name="${_file_name%.name}"
        echo "$_profile_name"
      fi
      ;;
    Linux)
      echo "$(systemctl list-units --type=service --state=active | grep -oP 'WireGuard via wg-quick.* for \K.*' | xargs)"
  esac
}

remoteSessionState() {
  if [[ ! -z "$(tmux showenv | grep '^SSH_CONNECTION')" ]]
  then
    echo '1'
  fi
}

kbState() {
  echo
}

case "$1" in
  is-remote-session) remoteSessionState ;;
  input-source)      inputSource ;;
  battery)           batteryState ;;
  k8s)               k8sState ;;
  kb)                kbState ;;
  wireguard)         wireguardState ;;
  cloudflare-env)    export SILVER_ASSERTED=yes; run cloudflare/tunnel/which env ;;
  cloudflare-region) export SILVER_ASSERTED=yes; run cloudflare/tunnel/which region ;;
  cloudflare-system) export SILVER_ASSERTED=yes; run cloudflare/tunnel/which system ;;
esac
