#!/usr/local/bin/bash

case $1 in

  new-session)
    _name="$2"
#   _name_padded=$(printf '%-20s ' "$_name" | tr '[:lower:]' '[:upper:]')
    _name_padded=$(echo "$_name" | tr '[:lower:]' '[:upper:]')

    if [[ ! -z "$_name" ]]
    then
      tmux new -s "${_name_padded}" -d
      tmux switch -t "${_name_padded}"
    fi
    ;;

  find-session)
    _part_of_name=$(echo "$2" | tr '[:lower:]' '[:upper:]')

    if [[ ! -z "$_part_of_name" ]]
    then
      tmux ls -F '#{session_name}' | tr '[:lower:]' '[:upper:]' | grep "$_part_of_name" | head -n 1 | xargs tmux switch -t
    fi
    ;;

  rename-window-to)
    echo "$2" | tr '[:lower:]' '[:upper:]' | xargs tmux rename-window
    ;;

  move-window-left)
    _index=$(tmux display-message -p '#I')
    tmux swap-window -s :$_index -t :$(( $_index - 1 )) &> /dev/null
    if [ $? -ne 0 ]
    then
      tmux swap-window -s :$_index -t :{session_windows}
    fi
    ;;

  move-window-right)
    _index=$(tmux display-message -p '#I')
    tmux swap-window -s :$_index -t :$(( $_index + 1 )) &> /dev/null
    if [ $? -ne 0 ]
    then
      tmux swap-window -s :$_index -t :1
    fi
    ;;

esac
